name: readme-activity

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Muhammedpyz
          COMMIT_MSG: "chore(readme): sync recent activity"
